version: "3.8"
services:
  neko:
    build:
      context: ./gamevm/john-wick-hex
      dockerfile: Dockerfile
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
    volumes:
      - /home/ec2-user/games:/games
    environment:
      - NEKO_SCREEN=1920x1080@30
      - NEKO_PASSWORD=neko
      - NEKO_PASSWORD_ADMIN=admin
      - NEKO_EPR=52000-52100
      - NEKO_ICELITE=1
      - APPPATH=/games/John-Wick-Hex
      - APPFILE='John Wick Hex.exe'